create table if not exists public.products (
  id bigint generated by default as identity primary key,
  article text unique not null,
  name text not null,
  price integer not null check (price >= 0),
  category text not null,
  description text,
  full_description text,
  img text,
  animal_types text[] not null default array['all']::text[],
  is_featured boolean not null default false,
  status text not null default 'available' check (status in ('available', 'preorder', 'out_of_stock')),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  items jsonb not null,
  total integer not null check (total >= 0),
  user_id uuid references auth.users (id),
  status text not null default 'new' check (status in ('new', 'completed', 'cancelled')),
  date text,
  created_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text not null,
  date text,
  image_url text,
  slug text unique not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_created_at on public.products (created_at desc);
create index if not exists idx_products_category on public.products (category);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_blog_posts_created_at on public.blog_posts (created_at desc);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.blog_posts enable row level security;

drop policy if exists "products_public_read" on public.products;
drop policy if exists "products_admin_insert" on public.products;
drop policy if exists "products_admin_update" on public.products;
drop policy if exists "products_admin_delete" on public.products;
drop policy if exists "blog_public_read" on public.blog_posts;
drop policy if exists "blog_admin_insert" on public.blog_posts;
drop policy if exists "blog_admin_update" on public.blog_posts;
drop policy if exists "blog_admin_delete" on public.blog_posts;
drop policy if exists "orders_public_insert" on public.orders;
drop policy if exists "orders_user_read_own" on public.orders;
drop policy if exists "orders_admin_read_all" on public.orders;
drop policy if exists "orders_admin_update" on public.orders;

create policy "products_public_read"
on public.products
for select
using (true);

create policy "products_admin_insert"
on public.products
for insert
with check ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "products_admin_update"
on public.products
for update
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz')
with check ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "products_admin_delete"
on public.products
for delete
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "blog_public_read"
on public.blog_posts
for select
using (true);

create policy "blog_admin_insert"
on public.blog_posts
for insert
with check ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "blog_admin_update"
on public.blog_posts
for update
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz')
with check ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "blog_admin_delete"
on public.blog_posts
for delete
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "orders_public_insert"
on public.orders
for insert
with check (true);

create policy "orders_user_read_own"
on public.orders
for select
using (user_id = auth.uid());

create policy "orders_admin_read_all"
on public.orders
for select
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');

create policy "orders_admin_update"
on public.orders
for update
using ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz')
with check ((auth.jwt() ->> 'email') = 'admin@zhasavet.kz');
