export const DEMO_PRODUCTS = [
  {
    article: 'ZV-001',
    name: 'Royal Canin Medium Adult 15кг',
    brand: 'Royal Canin',
    category: 'Корма и питание',
    animal_types: ['Собаки'],
    price: 28500,
    description: 'Сухой корм для взрослых собак средних пород от 1 до 7 лет',
    image_url: 'https://picsum.photos/id/429/600/600',
    rating: 4.8,
    reviews_count: 47,
  },
  {
    article: 'ZV-002',
    name: 'Hills Science Plan Kitten 7кг',
    brand: 'Hills',
    category: 'Корма и питание',
    animal_types: ['Кошки'],
    price: 19800,
    description: 'Сухой корм для котят до 1 года с курицей, поддерживает иммунитет и рост',
    image_url: 'https://picsum.photos/id/593/600/600',
    rating: 4.7,
    reviews_count: 33,
  },
  {
    article: 'ZV-003',
    name: 'Farmina N&D Grain Free Adult Cat 1.5кг',
    brand: 'Farmina',
    category: 'Корма и питание',
    animal_types: ['Кошки'],
    price: 12900,
    description: 'Беззерновой сухой корм для взрослых кошек с тунцом и апельсином',
    image_url: 'https://picsum.photos/id/488/600/600',
    rating: 4.9,
    reviews_count: 28,
  },
  {
    article: 'ZV-004',
    name: 'Grandorf Lamb & Turkey Adult Large 12кг',
    brand: 'Grandorf',
    category: 'Корма и питание',
    animal_types: ['Собаки'],
    price: 32000,
    description: 'Беззерновой корм для крупных пород с ягнёнком и индейкой, пробиотики в составе',
    image_url: 'https://picsum.photos/id/433/600/600',
    rating: 4.6,
    reviews_count: 21,
  },
  {
    article: 'ZV-005',
    name: 'Monge Dog Speciality Puppy Mini 800г',
    brand: 'Monge',
    category: 'Корма и питание',
    animal_types: ['Собаки'],
    price: 6500,
    description: 'Корм для щенков мини и малых пород с курицей и рисом, поддерживает развитие',
    image_url: 'https://picsum.photos/id/200/600/600',
    rating: 4.5,
    reviews_count: 15,
  },
  {
    article: 'ZV-006',
    name: 'Royal Canin Gastro Intestinal Cat 400г',
    brand: 'Royal Canin',
    category: 'Лекарства и фармацевтика',
    animal_types: ['Кошки'],
    price: 5800,
    description: 'Ветеринарная диетическая диета при расстройствах пищеварения у кошек',
    image_url: 'https://picsum.photos/id/145/600/600',
    rating: 4.7,
    reviews_count: 19,
  },
  {
    article: 'ZV-007',
    name: 'Frontline Spot On для собак (M) 3 пипетки',
    brand: 'Frontline',
    category: 'Антипаразитарные средства',
    animal_types: ['Собаки'],
    price: 4200,
    description: 'Капли на холку против блох, клещей и вшей для собак весом 10–20 кг',
    image_url: 'https://picsum.photos/id/225/600/600',
    rating: 4.6,
    reviews_count: 54,
  },
  {
    article: 'ZV-008',
    name: 'Bravecto таблетки для собак 10–20кг',
    brand: 'Bravecto',
    category: 'Антипаразитарные средства',
    animal_types: ['Собаки'],
    price: 8900,
    description: 'Жевательная таблетка от блох и клещей, защита до 12 недель',
    image_url: 'https://picsum.photos/id/326/600/600',
    rating: 4.9,
    reviews_count: 88,
  },
  {
    article: 'ZV-009',
    name: 'Stronghold капли для кошек до 2.5кг',
    brand: 'Stronghold',
    category: 'Антипаразитарные средства',
    animal_types: ['Кошки'],
    price: 2800,
    description: 'Против блох, клещей, гельминтов и ушного клеща для кошек',
    image_url: 'https://picsum.photos/id/237/600/600',
    rating: 4.8,
    reviews_count: 41,
  },
  {
    article: 'ZV-010',
    name: 'Мильбемакс таблетки для кошек 2 шт',
    brand: 'Novartis',
    category: 'Антипаразитарные средства',
    animal_types: ['Кошки'],
    price: 2100,
    description: 'Антигельминтный препарат широкого спектра действия для кошек и котят',
    image_url: 'https://picsum.photos/id/219/600/600',
    rating: 4.7,
    reviews_count: 36,
  },
  {
    article: 'ZV-011',
    name: 'Caniverm таблетки от глистов для КРС 10 табл',
    brand: 'Bioveta',
    category: 'Антипаразитарные средства',
    animal_types: ['КРС', 'МРС'],
    price: 3500,
    description: 'Антигельминтный препарат для крупного и мелкого рогатого скота',
    image_url: 'https://picsum.photos/id/312/600/600',
    rating: 4.5,
    reviews_count: 12,
  },
  {
    article: 'ZV-012',
    name: 'Canvit Biots S для собак 230г',
    brand: 'Canvit',
    category: 'Витамины и добавки',
    animal_types: ['Собаки'],
    price: 5600,
    description: 'Витаминно-минеральная добавка с пробиотиком для поддержания здоровья кишечника',
    image_url: 'https://picsum.photos/id/292/600/600',
    rating: 4.6,
    reviews_count: 23,
  },
  {
    article: 'ZV-013',
    name: 'Polidex Super Wool Plus таблетки 150 шт',
    brand: 'Polidex',
    category: 'Витамины и добавки',
    animal_types: ['Собаки', 'Кошки'],
    price: 3200,
    description: 'Витамины для укрепления шерсти, кожи и когтей у кошек и собак',
    image_url: 'https://picsum.photos/id/338/600/600',
    rating: 4.4,
    reviews_count: 61,
  },
  {
    article: 'ZV-014',
    name: 'Катозал 10% раствор для инъекций 100мл',
    brand: 'Bayer',
    category: 'Витамины и добавки',
    animal_types: ['КРС', 'МРС', 'Лошади'],
    price: 7800,
    description: 'Общеукрепляющий ветеринарный препарат для крупных животных, стимулятор обмена веществ',
    image_url: 'https://picsum.photos/id/249/600/600',
    rating: 4.8,
    reviews_count: 17,
  },
  {
    article: 'ZV-015',
    name: 'Шампунь Virbac Episoothe 250мл',
    brand: 'Virbac',
    category: 'Гигиена и уход',
    animal_types: ['Собаки', 'Кошки'],
    price: 4100,
    description: 'Успокаивающий шампунь с овсом и ретинолом для чувствительной кожи',
    image_url: 'https://picsum.photos/id/167/600/600',
    rating: 4.7,
    reviews_count: 29,
  },
  {
    article: 'ZV-016',
    name: 'Zymox Otic капли в уши с ферментами 14мл',
    brand: 'Zymox',
    category: 'Гигиена и уход',
    animal_types: ['Собаки', 'Кошки'],
    price: 3700,
    description: 'Капли для ушей с ферментной системой, борются с бактериями и дрожжами без антибиотиков',
    image_url: 'https://picsum.photos/id/399/600/600',
    rating: 4.8,
    reviews_count: 43,
  },
  {
    article: 'ZV-017',
    name: 'Лечебная попона послеоперационная S',
    brand: 'Kruuse',
    category: 'Гигиена и уход',
    animal_types: ['Собаки', 'Кошки'],
    price: 1900,
    description: 'Мягкая защитная попона для кошек и малых собак после операций, из дышащего материала',
    image_url: 'https://picsum.photos/id/375/600/600',
    rating: 4.3,
    reviews_count: 18,
  },
  {
    article: 'ZV-018',
    name: 'Левомеколь мазь 40г',
    brand: 'Нижфарм',
    category: 'Уход за ранами',
    animal_types: ['Собаки', 'Кошки', 'КРС', 'МРС', 'Лошади'],
    price: 890,
    description: 'Мазь с антибиотиком и метилурацилом для заживления ран и гнойных воспалений',
    image_url: 'https://picsum.photos/id/417/600/600',
    rating: 4.9,
    reviews_count: 112,
  },
  {
    article: 'ZV-019',
    name: 'Алюминиевый спрей Aluspray 200мл',
    brand: 'Vetoquinol',
    category: 'Уход за ранами',
    animal_types: ['КРС', 'МРС', 'Лошади', 'Собаки'],
    price: 3200,
    description: 'Аэрозоль для защиты ран, отпугивает мух, образует защитную плёнку с антисептиком',
    image_url: 'https://picsum.photos/id/408/600/600',
    rating: 4.7,
    reviews_count: 25,
  },
  {
    article: 'ZV-020',
    name: 'Purina Pro Plan Veterinary Diets EN 400г',
    brand: 'Purina',
    category: 'Лекарства и фармацевтика',
    animal_types: ['Собаки'],
    price: 4900,
    description: 'Ветеринарная диета для собак с воспалительными заболеваниями кишечника',
    image_url: 'https://picsum.photos/id/139/600/600',
    rating: 4.6,
    reviews_count: 14,
  },
  {
    article: 'ZV-021',
    name: 'Поводок-рулетка Flexi New Classic 5м',
    brand: 'Flexi',
    category: 'Аксессуары и оборудование',
    animal_types: ['Собаки'],
    price: 5500,
    description: 'Рулетка для собак до 15кг, длина 5м, лента 15мм, эргономичная ручка',
    image_url: 'https://picsum.photos/id/180/600/600',
    rating: 4.5,
    reviews_count: 39,
  },
  {
    article: 'ZV-022',
    name: 'Когтеточка угловая с игрушкой 60см',
    brand: 'Trixie',
    category: 'Аксессуары и оборудование',
    animal_types: ['Кошки'],
    price: 3800,
    description: 'Угловая когтеточка из сизаля для крепления на стены или мебель, с мышкой',
    image_url: 'https://picsum.photos/id/337/600/600',
    rating: 4.4,
    reviews_count: 31,
  },
  {
    article: 'ZV-023',
    name: 'Лакомство Dreamies для кошек курица 60г',
    brand: 'Dreamies',
    category: 'Лакомства',
    animal_types: ['Кошки'],
    price: 790,
    description: 'Хрустящие подушечки с нежной начинкой из курицы, без красителей',
    image_url: 'https://picsum.photos/id/429/600/600',
    rating: 4.9,
    reviews_count: 204,
  },
  {
    article: 'ZV-024',
    name: 'Сено луговое прессованное Timothy 500г',
    brand: 'Versele-Laga',
    category: 'Корма и питание',
    animal_types: ['Хомяки и грызуны', 'Мелкие питомцы'],
    price: 1200,
    description: 'Натуральное луговое сено тимофеевки для кроликов, морских свинок и шиншилл',
    image_url: 'https://picsum.photos/id/142/600/600',
    rating: 4.6,
    reviews_count: 52,
  },
  {
    article: 'ZV-025',
    name: 'Комбикорм для лошадей «Конный двор» 25кг',
    brand: 'Конный двор',
    category: 'Корма и питание',
    animal_types: ['Лошади'],
    price: 6800,
    description: 'Сбалансированный комбикорм для спортивных и рабочих лошадей с витаминно-минеральным премиксом',
    image_url: 'https://picsum.photos/id/582/600/600',
    rating: 4.7,
    reviews_count: 8,
  },
];